version: '3'

services:
  web:
    container_name: "react-ts"
    build: .
    ports:
     - "4200:4200"
    volumes:
     - "/Users/a39/Desktop/other/react-ts/docker/nginx/conf.d:/etc/nginx/conf.d:rw"