version: '3'

services:
  ts:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "react-ts"
    ports:
     - "4200:4200"
    volumes:
     - "/39/ci-demo-project/docker/volume/conf.d:/etc/nginx/conf.d:rw"