version: '3'

services:
  web:
    container_name: "my-nginx"
    build: .
    ports:
     - "4000:4000"
    volumes:
     - "/Users/a39/Desktop/other/react-ts/docker/nginx/conf.d:/etc/nginx/conf.d:rw"